Democode/05_ViewComponentsExample_end/ViewComponentsExample/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ViewComponentsExample.Services;

namespace ViewComponentsExample.Controllers
{
    public class HomeController : Controller
    {
        IPersonProvider _personProvider;

        public HomeController(IPersonProvider personProvider)
        {
            _personProvider = personProvider;
        }

        public IActionResult Index()
        {
            ViewBag.Rows = 5;
            ViewBag.Columns = 3;
            ViewBag.People = _personProvider.PersonList;
            return View();
        }
    }
}

Democode/05_ViewComponentsExample_end/ViewComponentsExample/ViewComponents/PersonCardViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ViewComponentsExample.ViewComponents
{
    public class PersonCardViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(int id)
        {
            return Task.FromResult<IViewComponentResult>(View("CardDesign", id));
        }
    }
}

Democode/05_ViewComponentsExample_end/ViewComponentsExample/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="css\style.css" rel="stylesheet" />
</head>
<body>
    <h1>Person Card List</h1>
    <table>
        @for (int rowIndex = 0; rowIndex < ViewBag.Rows; rowIndex++)
        {
            <tr>
                @for (int columnIndex = 0; columnIndex < ViewBag.Columns; columnIndex++)
                {
                    int cardIndex = columnIndex + (rowIndex * ViewBag.Columns);
                    @await Component.InvokeAsync("PersonCard", cardIndex);
                }
            </tr>
        }
    </table>
</body>
</html>

Democode/05_ViewComponentsExample_end/ViewComponentsExample/Views/Shared/Components/PersonCard/CardDesign.cshtml
@model int
<td>
    <div>First Name: @ViewBag.People[Model].FirstName</div>
    <div>Last Name: @ViewBag.People[Model].LastName</div>
    <div>Residence: @ViewBag.People[Model].Address</div>
    <div>Phone: @ViewBag.People[Model].PhoneNumber</div>
</td>