Labfiles/01_CitiesWebsite_end/CitiesWebsite/Models/City.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CitiesWebsite.Models
{
    public class City
    {
        public string Country { get; }
        public string Name { get; }
        public string TimeZone { get; }
        public CityPopulation Population { get; }

        public City(string country, string cityName, string timeZone, CityPopulation population)
        {
            Country = country;
            Name = cityName;
            TimeZone = timeZone;
            Population = population;
        }
    }
}

Labfiles/01_CitiesWebsite_end/CitiesWebsite/Models/CityPopulation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CitiesWebsite.Models
{
    public class CityPopulation
    {
        public int Year { get; }
        public int City { get; }
        public int Urban { get; }
        public int Metro { get; }

        public CityPopulation(int year, int city, int urban, int metro)
        {
            Year = year;
            City = city;
            Urban = urban;
            Metro = metro;
        }
    }
}

Labfiles/01_CitiesWebsite_end/CitiesWebsite/Controllers/CityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CitiesWebsite.Services;

namespace CitiesWebsite.Controllers
{
    public class CityController : Controller
    {
        private ICityProvider _cities;

        public CityController(ICityProvider cities)
        {
            _cities = cities;
        }

        public IActionResult ShowCities()
        {
            ViewBag.Cities = _cities;
            return View();
        }

        public IActionResult ShowDataForCity(string cityName)
        {
            ViewBag.City = _cities[cityName];
            return View();
        }

        public IActionResult GetImage(string cityName)
        {
            return File($@"images\{cityName}.jpg", "image/jpeg");
        }
    }
}

Labfiles/01_CitiesWebsite_end/CitiesWebsite/ViewComponents/CityViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CitiesWebsite.Services;
using CitiesWebsite.Models;

namespace CitiesWebsite.ViewComponents
{
    public class CityViewComponent : ViewComponent
    {
        private ICityProvider _cities;

        public CityViewComponent(ICityProvider cities)
        {
            _cities = cities;
        }

        public async Task<IViewComponentResult> InvokeAsync(string cityName)
        {
            ViewBag.CurrentCity = await GetCity(cityName);
            return View("SelectCity");
        }

        private Task<City> GetCity(string cityName)
        {
            return Task.FromResult<City>(_cities[cityName]);
        }
    }
}

Labfiles/01_CitiesWebsite_end/CitiesWebsite/Views/City/ShowCities.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ShowCities</title>
    <link rel="stylesheet" type="text/css" href="~/css/style.css" />
</head>
<body>
    <h1>Select City</h1>
    @foreach (var item in ViewBag.Cities)
    {
        @await Component.InvokeAsync("City", item.Key)
    }
</body>
</html>

Labfiles/01_CitiesWebsite_end/CitiesWebsite/Views/City/ShowDataForCity.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ShowDataForCity</title>
    <link rel="stylesheet" type="text/css" href="~/css/style.css" />
</head>
<body>
    <div>
        <h2>@ViewBag.City.Name</h2>
        <p>Country: @ViewBag.City.Country</p>
        <p>Time zone: @ViewBag.City.TimeZone</p>
        <span><img src="@Url.Action("GetImage", new { cityName = ViewBag.City.Name })" /></span>
        @await Html.PartialAsync("_CityPopulation")
        <a asp-action="ShowCities">Back</a>
    </div>
</body>
</html>